/*

   [ CREATE BY DANZY AVAILABLE ]
   [ BUY SC/UP PANGKAT? HUBUNGI t.me/ortulue ]
   [ NOTE : JOIN PARTNER PRIBADI DANZY FREE AKSES RESELLER SCRIPT DANZY XVISIBLE & AKSES OWNER SCRIPT FETRIX BLAZER !! ]
   
*/
module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN || "",
  OWNER_IDS: ["8682445029"]
};